перемещение главного пина по карте
htmlacademy-javascript/1466459-keksobooking-21 pull request #7
Opened 2020-11-09 17:15 UTC by andreysereda1976

добавил обработку перемещения главного пина по карте с изменением адреса (модуль pin-move.js)

2020-11-09 17:19 UTC, andreysereda1976 commented on js/pin-move.js
> +    minY: 115,
пункт 5.4 ТЗ требует ограничить Y для адреса параметрами от 130 до 630 (соответственно 46 и 546 для верхнего левого угла кнопки, т.к. ее высота 84), но это глупо - тогда пин висит в воздухе в верхней позиции и не дотягивается до низа карты в нижней. поменял эти параметры по своему усмотрению

2020-11-09 17:21 UTC, andreysereda1976 commented on js/pin-move.js
> +    const onMouseUp = (upEvt) => {
В задании написано, что для mousup тоже нужно делать проверку адреса, но я не понял, зачем, - оно работает и без такой проверки (как при движении мыши перед отпусканием кнопки, так и без него). не стал делать

2020-11-09 17:22 UTC, andreysereda1976 commented on js/pin-move.js
> +
пришлось сделать эти две проверки. не придумал, как короче можно ограничить границы передвижения пина

2020-11-10 17:03 UTC, maxim-usikov requested changes

2020-11-10 17:03 UTC, maxim-usikov commented on js/pin-move.js
> +    const onMouseUp = (upEvt) => {
Надо сделать. Если я просто кликну по пину координаты запишутся? будет ли событие мув? 

При простом клике по метке события мув не будет и адрес не установится из mouseUp. Он у тебя устанавливается на активацию / дезактивацию страницы - что не совсем корректно пока что.

> Учтите, расчёт координат метки и их запись в поле адреса должна дублироваться и в обработчике mouseup, потому что в некоторых случаях пользователь может нажать мышь на метке, но никуда её не переместить. Напишите универсальную функцию расчёта координат, чтобы избавиться от дублирования кода.

2020-11-12 08:52 UTC, merged